
# Staging Environment Configuration
server {
    listen 8081;
    server_name _; # Responds to IP:8081 or Domain:8081

    access_log /var/log/nginx/wqt-staging.access.log;
    error_log /var/log/nginx/wqt-staging.error.log;

    location / {
        proxy_pass http://127.0.0.1:3001; # Proxy to Node app on internal port 3001
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
